tests/libssh2_config_cmake.h.in, tests/openssh_fixture.c
This PR supersede #126 , it closes #125
=> HAVE_NETINET_IN_H was not defined correctly for the tests

src/wincng.h
Fixed missing defines preventing building
=> Added ECDSA defines

src/openssl.c, src/openssl.h, src/pem.c
Hi maintainer,
This new PR is based on #198, please help review/revise improper code.
Thanks!
Jun
=> Fix the EVP cipher meth memory leakage problem

include/libssh2.h
=> removed INT64_C define

src/crypto.h, src/hostkey.c, src/openssl.c
Accidentally had OpenSSL calls in hostkey.c
=> Abstracted OpenSSL calls out of hostkey.c

src/crypto.h, src/hostkey.c, src/openssl.c
fixed warnings in ed25519 implementation
=> fixed type warnings

RELEASE-NOTES, include/libssh2.h, src/channel.c, src/kex.c, src/packet.c, src/session.c, src/transport.c, src/userauth.c
Fixes from code review by Canonical.
=> 1.8 Security fixes

src/comp.c, src/packet.c, src/sftp.c, src/transport.c
More fixes from code review by Canonical.
=> More 1.8.0 security fixes

include/libssh2.h, src/channel.c, src/hostkey.c, src/kex.c, src/packet.c, src/session.c, src/transport.c, src/userauth.c
Fixes from code review by Canonical along with a more in-depth audit of API usage.
=> Security fixes

src/userauth.c
Fixes for user auth failure on the 1.8.1 patched branch.
=> Fixed misapplied patch

src/pem.c
This is an OpenSS_H_ format, not anything to do with OpenSS_L_.
=> Fixup spelling in comments/constants.

.editorconfig
Simple start to an editor config file when editing source files to make sure they are configured correctly.
=> Editorconfig file for source files

src/misc.c
=> Add an EWOULDBLOCK check for better portability

src/packet.c
file: packet.c
notes:
improved bounds checking in packet_queue_listener.
=> packet.c: improved packet parsing in packet_queue_listener

src/packet.c
Use new API to parse data in packet_x11_open() for better bounds checking.
=> packet.c: improved parsing in packet_x11_open()

.travis.yml
Attempt to use build-in Chrome installing instead of using a failing command.
=> Fix Chrome installing

README.md
=> Update INSTALL_MAKE path to INSTALL_MAKE.md

src/openssl.c
minor changes of coding style and align conditional preprocessor. make build condition consistent.
Thanks!
=> minor changes of coding style

src/os400qc3.c, src/os400qc3.h
Fixes #426 
Thanks in advance for merging.
=> Make it compilable again on OS400.

tests/openssh_fixture.c, tests/ssh2.c, tests/test_agent_forward_succeeds.c, tests/test_hostkey.c, tests/test_hostkey_hash.c, tests/test_keyboard_interactive_auth_fails_with_wrong_response.c, tests/test_keyboard_interactive_auth_succeeds_with_correct_response.c, tests/test_password_auth_fails_with_wrong_password.c, tests/test_password_auth_fails_with_wrong_username.c, tests/test_password_auth_succeeds_with_correct_credentials.c, tests/test_public_key_auth_fails_with_wrong_key.c, tests/test_public_key_auth_succeeds_with_correct_dsa_key.c, tests/test_public_key_auth_succeeds_with_correct_ed25519_key.c, tests/test_public_key_auth_succeeds_with_correct_ed25519_key_from_mem.c, tests/test_public_key_auth_succeeds_with_correct_encrypted_ed25519_key.c, tests/test_public_key_auth_succeeds_with_correct_encrypted_rsa_key.c, tests/test_public_key_auth_succeeds_with_correct_rsa_key.c, tests/test_public_key_auth_succeeds_with_correct_rsa_openssh_key.c
Follow up to 2764bc8e06d51876b6796d6080c6ac51e20f3332
=> tests: satisfy checksrc regarding max line length of 79 chars

tests/Makefile.am
REf: https://github.com/libssh2/libssh2/issues/457#issuecomment-676825463
=> tests: include all test files in the dist

docs/HACKING.CRYPTO, include/libssh2.h, src/channel.c, src/kex.c, src/libgcrypt.h, src/openssl.h, src/os400qc3.c, src/os400qc3.h, src/transport.c
This fixes #519. Please see the issue & commit messages for more info.
=> Fix _libssh2_random silently discarding errors

tests/openssh_fixture.c
Hello,
The current tests suite starts SSH server as OCI container. This commit
add the possibility to run the tests in a container provided that:
* the docker client is installed builder container
* the host docker daemon unix socket has been mounted in the builder
container (with, if needed, the DOCKER_HOST environment variable
accordingly set, and the permission to write on this socker)
* the builder container is run on the default bridge network, or the
host network. This PR does not handle the case where the builder
container is on another network.
Notes about the implementation:
* I used `getline` function which has been standardized in 2008 (POSIX). It maybe does not reach the portability criteria but as it aims at being built in a docker container it should be ok. Tell me if you …
=> [tests] Allow the tests to run inside a container

tests/openssh_fixture.c
Hello,
Sometimes, as the OCI container is run in detached mode, it is possible
the actual server is not ready yet to handle SSH traffic. The goal of
this PR is to try several times (max 3). The mechanism is the same as
for the connection to the docker machine.
Regards,
=> [tests] Try several times to connect the ssh server

.github/workflows/ci.yml
Also removed 32 bit building in the matrix. We'll see how this goes...
=> Update CI to use latest Ubuntu #624

src/agent.c
=> agent: handle overly large comment lengths

docs/CMakeLists.txt, docs/HACKING-CRYPTO, docs/Makefile.am, docs/libssh2_crypto_engine.3, include/libssh2.h, src/version.c
Proposition of an API to let the programmer know which crypto engine is used in libssh2
=> Runtime engine detection

src/hostkey.c, src/misc.c, src/misc.h
=> Ensure KEX replies don't include extra bytes

src/kex.c
=> Update for typo fix #697

tests/session_fixture.c
via `export FIXTURE_TRACE_ALL=1`.
=> tests: add option to enable all trace messages in fixture

src/openssl.c
The behavior is different which is causing it to not work as expected.
=> Revert usage of EVP_CipherUpdate #764 #739

tests/openssh_fixture.c
via `export OPENSSH_NO_DOCKER=1`.
SSH server host can be set via:
`export OPENSSH_SERVER_HOST=127.0.0.1`
SSH server port via existing:
`export OPENSSH_SERVER_PORT=4711`
This requires more work to be usable out of the box. The necessery sshd config is (partly) embedded into `tests/openssh_server/Dockerfile`.
After this patch, it is possible to run tests in envs where docker is not installed or not available, by running a preconfigured, non-containerized sshd.
Diff without whitespaces: https://github.com/libssh2/libssh2/pull/762/files?w=1
=> tests: add option to run tests without docker

src/misc.c
=> Add NULL session check to _libssh2_error_flags()

docs/INSTALL_CMAKE.md
Follow-up to 505ea626b6e125b7ce15caf453b522192008a884
=> cmake: reflect minimum version in docs

win32/GNUmakefile, win32/rules.mk, win32/test/GNUmakefile
Also strip stray newlines from `win32/rules.mk`.
=> win32: convert tabs to spaces [ci skip]

win32/GNUmakefile, win32/test/GNUmakefile
- indent
- sync `test/GNUmakefile` with main
- delete `RANLIB`
- use `else if`
- use more `?=`
=> GNUmakefile: cleanups [ci skip]

.gitignore, maketgz
Copied from curl:
https://github.com/curl/curl/blob/4528690cd51e5445df74aef8f83470a602683797/maketgz#L174-L222
=> maketgz: add .xz, .bz2, .zip source archive formats

git2news.pl, maketgz, tests/mansyntax.sh, tests/ossfuzz/ossfuzz.sh, tests/ssh2.sh, tests/sshd_fixture.sh.in, tests/sshdwrap
- fix shellcheck warnings
- use quotes
- use `$()`
- use `printf` (instead of calling perl)
- indent
- copy/adapt header comment from curl to `maketgz`
=> tidy-up: scripts

include/libssh2.h, include/libssh2_publickey.h, include/libssh2_sftp.h
Without whitespace: https://github.com/libssh2/libssh2/pull/948/files?w=1
=> include: indentation fixes

.github/workflows/ci.yml
https://github.com/Mbed-TLS/mbedtls/releases/tag/v3.4.1
=> ci: bump mbedtls

.github/workflows/ci.yml
=> ci: add reproducibility test for `maketgz`

.github/workflows/ci.yml
Install verification based on:
https://github.com/curl/curl/blob/28c5ddf13ac311d10bc4e8f9fc4ce0858a19b888/scripts/installcheck.sh
Closes #1362
=> ci: verify build and install from tarball

appveyor.yml
Ref: 104744f4a523de574ce3767c50948d9b8385be4c #1348
=> ci/appveyor: re-enable OpenSSL 3, also bump to 3.2.1

src/kex.c, src/libssh2_priv.h, src/session.c
Original fix submitted as a patch by Trzik.
Fixes #1404.
=> Fix a memory leak in key exchange.

.github/workflows/ci.yml
=> ci/GHA: FreeBSD 14.1, actions bump

.github/workflows/ci.yml
Follow-up to e973493f992313b3be73f51d3f7ca6d52e288558 #1393
=> ci/GHA: simplify mbedTLS build hack for autotools

src/mbedtls.c
Fix regression with commit from #1421
=> Correctly initialize values

.github/workflows/ci.yml, docs/INSTALL_AUTOTOOLS, docs/INSTALL_CMAKE.md
=> tidy-up: link updates

src/kex.c
NULL server hostkey based on fuzzer failure case.
=> Prevent possible double free of hostkey

src/kex.c, src/libssh2_priv.h
=> Remove unused kex state variable `exchange_hash`
