src/agent.c

"agent_disconnect_unix", called by "libssh2_agent_disconnect", was
leaving the file descriptor in the agent structure unchanged. Later,
"libssh2_agent_free" would call again "libssh2_agent_disconnect" under
the hood and it would try to close again the same file descriptor. In
most cases that resulted in just a harmless error, but it is also
possible that the file descriptor had been reused between the two
calls resulting in the closing of an unrelated file descriptor.
This patch sets agent->fd to LIBSSH2_INVALID_SOCKET avoiding that
issue.
Signed-off-by: Salvador Fandiño <sfandino@yahoo.com>

agent_disconnect_unix: unset the agent fd after closing it

---

win32/libssh2_config.h

For _MSC_VER == 1900 these macros are not needed and create problems:
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition (compiling source file libssh2-files\src\mac.c)
1> \win32\libssh2_config.h(27): note: see previous definition of 'snprintf' (compiling source file libssh2-files\src\mac.c)
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error: Macro definition of snprintf conflicts with Standard Library function declaration (compiling source file libssh2-files\src\mac.c)

Fix MSVC 14 compilation errors

---

src/kex.c

Ported SHA256 fix to SHA1 until a better fix is committed.

Fix for security issue CVE-2016-0787

---

src/session.c

If `_libssh2_wait_socket` only sets `err_code` then `err_msg` can be left with a stale and misleading error message. For example, if a blocking call is made then `err_msg` will contain a "Would block..." message. This is confusing to the user if they call `libssh2_session_last_error` to get an error description.

Set err_msg on _libssh2_wait_socket errors

---

src/session.c

Fix comparison with api_timeout to use milliseconds

---

include/libssh2.h
src/channel.c

commit 8e9e70d514619c8ceabfa852444ad40ffbf8c0d9
Author: Salvador Fandino sfandino@yahoo.com
Date:   Mon May 9 13:48:31 2016 +0200
```
channel_wait_eof: handle receive window exhaustion
Until now, if the remote receiving window is exhausted this function
hangs forever as data is not read and the remote side just keeps
waiting for the window to grow before sending more data.
This patch, makes this function check for that condition and abort
with an error when it happens.
```
commit 311a4f1fc7d4003eb56afe02f1c80d7f383cdb2d
Author: Salvador Fandino sfandino@yahoo.com
Date:   Mon May 9 13:20:40 2016 +0200
```
channel_wait_closed: don't fail when unread data is queued
This function was calling channel_wait_eof to ensure that the EOF
packet has already been received, but that function also …
```

Unfussy wait closed

---

src/sftp.c

1>  sftp.c
1>libssh2-files\src\sftp.c(3393): warning C4456: declaration of 'retcode' hides previous local declaration
1>  libssh2-files\src\sftp.c(3315): note: see declaration of 'retcode'

Fix MSVC 14 compilation warning

---

docs/libssh2_channel_wait_eof.3

channel_wait_eof waits for channel->remote.eof, which is set on
receiving a `SSH_MSG_CHANNEL_EOF` message. This message is sent
when a party has no more data to send on a channel.
See https://github.com/alexcrichton/ssh2-rs/issues/34#issuecomment-184850856 if you want a complete run-through of me coming to this conclusion

docs: correctly describe channel_wait_eof

---

src/sftp.c

The problem is that the original if statement simply returns NULL, but does not set the session last error code. The consequence is that libssh2_sftp_init() also returns NULL and libssh2_session_last_errno(sshSession) == LIBSSH2_ERROR_NONE.
In my test the LIBSSH2_ERROR_EAGAIN is coming from sftp.c row 337:
if(4 != sftp->partial_size_len)
/\* we got a short read for the length part */
return LIBSSH2_ERROR_EAGAIN;
with "partial_size_len == 0". Not sure if this is expected.

libssh2_sftp_init hang: last error not set

---

acinclude.m4

The change fixes passing of bogus gcrypt prefix.
Reproducible as:
$ ./configure --with-libgcrypt
$ make V=1
...
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2 -Iyes/include -version-info 1:1:0 -no-undefined -export-symbols-regex '^libssh2_.*' -lgcrypt  -lz -Lyes/lib -o libssh2.la -rpath /usr/local/lib channel.lo comp.lo crypt.lo hostkey.lo kex.lo mac.lo misc.lo packet.lo publickey.lo scp.lo session.lo sftp.lo userauth.lo transport.lo version.lo knownhost.lo agent.lo libgcrypt.lo pem.lo keepalive.lo global.lo   -lgcrypt
../libtool: line 7475: cd: yes/lib: No such file or directory
libtool:   error: cannot determine absolute directory name of 'yes/lib'
These
-Iyes/include
-Lyes/lib
come from libgcrypt code autodetection:
if test -n "$use_libgcrypt" && test "$use_libgcrypt" != "no"; …

acinclude.m4: fix ./configure --with-libgcrypt

---

docs/HACKING.CRYPTO
os400/initscript.sh
src/kex.c
src/libgcrypt.h
src/libssh2_priv.h
src/openssl.h
src/os400qc3.c
src/os400qc3.h
src/wincng.h

Hi,
The CVE-2016-0787 fixes broke libssh2 on os400.
This pull request makes it work again.
See comment of commit 0b482a378f23d82b4dca104373d341bb423e501a and HACKING.CRYPTO for more information.
I tested it successfully with all crypto backends except wincng (not tested).
Thanks for pulling,
Patrick

Make libssh2 work again on os400.

---

src/mbedtls.h

Sorry for that problem: mbedTLS backend was not yet implemented at the previous PR time.
This commit should fix https://travis-ci.org/libssh2/libssh2/jobs/175349805.
Tested locally: OK.

Define new Diffie-Hellman context for mbedTLS

---

tests/CMakeLists.txt

In tests/openssh_fixture.c, the system header netinet/in.h is included if it was determined to exist. However, no such check for existence was actually being performed, so `#ifdef HAVE_NETINET_IN_H` is always false in the tests. This was causing problems on FreeBSD, since it didn't know about `sockaddr_in` without that header.

Check for netinet/in.h in the tests CMake file

---

docs/HACKING.CRYPTO
src/kex.c
src/libgcrypt.c
src/libgcrypt.h
src/mbedtls.c
src/mbedtls.h
src/openssl.c
src/openssl.h
src/wincng.c
src/wincng.h

This implements what has been suggested in https://github.com/libssh2/libssh2/pull/118 on Aug, 19.
Not all backends feature the low level API needed to compute a Diffie-Hellman
secret, but some of them directly implement Diffie-Hellman support with opaque
private data. The later approach is now generalized and backends are
responsible for all Diffie Hellman computations.
As a side effect, procedures/macros _libssh2_bn_rand and _libssh2_bn_mod_exp
are no longer needed outside the backends.
Tested locally with openssl, libgcrypt and mbedtls successfully. os400qc3 unaltered (was already compatible).
wincng carefully changed, but untested.

Implement Diffie-Hellman computations in crypto backends.

---

src/openssl.h

Need to use EVP_CIPHER_CTX_free instead of EVP_CIPHER_CTX_reset.

Fix memory leak of crypt_ctx->h using openSSL 1.1+

---

include/libssh2.h
src/hostkey.c
src/kex.c
src/libssh2_priv.h

This commit adds SHA256 host key fingerprint support. This has been the default since OpenSSH 6.8 and now that libssh2 has SHA256 as a crypto lib requirement, this commit should not cause too much trouble.
Because libssh2 computes the host key hash during the kex, we don't know (a priori) if SHA1 or SHA256 fingerprints will be used, if at all, so we need to compute both. This is also true for MD5 fingerprints, if enabled.
(This replaces my previous PR and incorporates willco007's suggestion (and code!) to use base64 fingerprints in the debug output as to mimic OpenSSH behavior.)

Add support for SHA256 hostkey fingerprints

---

src/openssl.c
src/openssl.h

When building with OPENSSL_API_COMPAT=0x10100000L, OpenSSL_add_all_algorithms
and OpenSSL_add_all_ciphers don't exist. The corresponding functionality is
handled automatically with OpenSSL 1.1.

openssl: fix build with OpenSSL 1.1 API

---

src/openssl.c
src/openssl.h

Load the ciphers in init instead of lazily to avoid threading issues described in #188

Fix for #188

---

src/openssl.c

after e378d2e30a40bd9bcee06dc3a4250f269098e200

openssl.c: remove no longer used variable

---

src/scp.c

It breaks SCP download/upload from/to certain server implementations.
The bug does not manifest with OpenSSH, which silently drops the NUL
byte (eventually with any garbage that follows the NUL byte) before
executing it.
Bug: https://bugzilla.redhat.com/1489736

scp: do not NUL-terminate the command for remote exec

---

src/pem.c

If an invalid PEM file is read and the lines are longer than 128 characters it will go out of bounds and crash on line 91.

Fixes out of bounds memory access

---

src/crypt.c

Master branch cmake compile currently failing with 
```
src/crypt.c:57:5: error: expected ‘}’ before numeric constant
8,                     /* blocksize (SSH2 defines minimum blocksize as 8) */
^
```

Fix typo in crypt.c

---

tests/openssh_fixture.c
tests/runner.c
tests/session_fixture.c
tests/simple.c
tests/ssh2.c
tests/test_hostkey.c
tests/test_hostkey_hash.c
tests/test_keyboard_interactive_auth_fails_with_wrong_response.c
tests/test_keyboard_interactive_auth_succeeds_with_correct_response.c
tests/test_password_auth_fails_with_wrong_password.c
tests/test_password_auth_fails_with_wrong_username.c
tests/test_password_auth_succeeds_with_correct_credentials.c
tests/test_public_key_auth_fails_with_wrong_key.c
tests/test_public_key_auth_succeeds_with_correct_dsa_key.c
tests/test_public_key_auth_succeeds_with_correct_encrypted_rsa_key.c
tests/test_public_key_auth_succeeds_with_correct_rsa_key.c

Also:
* add 'static' qualifier to file-wide const buffers
* fix a non-ANSI C89 comment
* silence a mismatched fprintf() mask warning by adding a cast

tests: fix checksrc warnings

---

src/mbedtls.c
src/mbedtls.h

These handles are only used in `mbedtls.c`, and CodeWarrior (on classic MacOS) throws multiple-definition linker errors when they're defined in the header file

mbedTLS: Avoid multiple definition errors for context handles

---

src/mbedtls.c
src/mbedtls.h

fix memory leak

---

docs/INSTALL_AUTOTOOLS

I've previously only built libssh2 from tarballs, and it took me a lot of time to figure out how to build from master. 
Then I discovered that all I needed to do was call `./buildconf`
This pull request updates the build instructions to mention this.
(See also #221)

Add Instructions for building from Master

---

include/libssh2.h
src/hostkey.c
src/knownhost.c
src/openssl.c
tests/test_hostkey.c
tests/test_hostkey_hash.c

Issue was brough up in pull request #248. Also added ECDSA call to _libssh2_pub_priv_keyfilememory().

ECDSA key types are now explicit

---

src/openssl.c

This commit fixes linking against an OpenSSL library that was compiled with
`no-engine` support by bypassing the initialization routines as they won't be
available anyway.

Fix OpenSSL link error with `no-engine` support

---

src/openssl.c

When dereferencing from *aes_ctr_cipher, being a pointer itself,
ambiguity can occur with compiler and build can fail reporting:
openssl.c:574:20: error: ‘*aes_ctr_cipher’ is a pointer; did you mean to use ‘->’?
*aes_ctr_cipher->nid = type;
Sorround every *aes_ctr_cipher-> occurence with paranthesis like this
(*aes_ctr_cipher)->
Signed-off-by: Giulio Benetti <giulio.benetti@micronovasrl.com>

openssl: fix dereferencing ambiguity potentially causing build failure

---

include/libssh2_sftp.h
src/sftp.c

Added constant LIBSSH2_SFTP_DEFAULT_MODE to use the server default permissions when making a new directory

Allow default permissions to be used in sftp_mkdir

---

src/misc.c

This is necessary for compiling libgit2 with SSH support on 32-bit windows

Fix error compiling on Win32 with STDCALL=ON

---

src/mbedtls.c

Some of the leaks present on version 1.8.0 have been solved, but still there was one more leak.
Running tests before/after the patch can verify that the leak is solved with this simple modification.
Best regards,
Adrian M.

mbedtls: Fix leak of 12 bytes by each key exchange.

---

src/sftp.c

Otherwise the previous "LIBSSH2_SFTP_DEFAULT_MODE" won't have any effect.

Fix https://github.com/libssh2/libssh2/pull/271

---

src/sftp.c

to match implementations like OpenSSH

SFTP: increase maximum packet size to 256K

---

docs/libssh2_hostkey_hash.3

LIBSSH_HOSTKEY_HASH_SHA256 exists, but was not documented.

docs: update libssh2_hostkey_hash.3 [ci skip]

---

src/misc.c

Use LIBSSH2_FREE() here, not free(). We allow memory function
replacements so free() is rarely the right choice...

_libssh2_string_buf_free: use correct free

---

src/userauth.c

userauth: fix "Function call argument is an uninitialized value"

---

tests/test_hostkey_hash.c

Silence warnings about unused variables in this test

Silence unused var warnings

---

src/misc.c

Misc.c : _libssh2_check_length()
Ensure the requested length is less than the total length before doing the additional bounds check

_libssh2_check_length() : additional bounds check

---

src/misc.c

misc.c : _libssh2_check_length()
Removed cast and one-lined check. 
Credit : Yuriy M. Kaminskiy

Simplified _libssh2_check_length

---

docs/CMakeLists.txt
docs/Makefile.am
docs/libssh2_agent_get_identity_path.3
docs/libssh2_agent_set_identity_path.3
include/libssh2.h
src/agent.c

Libssh2 uses the `SSH_AUTH_SOCK` env variable to read the system agent location. However, when using a custom agent path you have to set this value using `setenv` which is not thread-safe. The new functions allow for a way to set a custom agent socket path which is thread safe.

Added agent functions libssh2_agent_get_identity_path() and libssh2_a gent_set_identity_path()

---

src/sftp.c

To allow subsequent reads on the channel.

SFTP: discard oversized packet

---

src/session.c

Prevent banner_receive() from leaking when accessing non ssh ports

---

src/mbedtls.c

@willco007 
Thanks a lot!
The "trailing whitespaces" from https://github.com/libssh2/libssh2/pull/358

mbedtls: allow private-key from memory

---

src/hostkey.c
src/kex.c
src/libssh2_priv.h
src/misc.c
src/misc.h
src/openssl.c
src/pem.c
src/sftp.c

Renamed `_libssh2_get_c_string` to `_libssh2_get_string` and now returns -1 on error and 0 on success. Also changed `_libssh2_get_bignum_bytes` to return -1 on error and 0 on success. Both now take `size_t` as a parameter to return the length of the buffer. This is to attempt to keep the data going in/out of these functions unsigned to better impedance match the existing API.

String buffer improvements

---

src/transport.c

file : transport.c
notes : move local `total_num` variable inside of if block to prevent scope access issues which caused #360.

transport.c : scope local total_num var

---

src/kex.c
src/libssh2_priv.h
src/misc.c
src/misc.h

Added _libssh2_copy_string() to misc.c to return an allocated and filled char buffer from a string_buf offset. Removed no longer needed s var in kmdhgGPshakex_state_t.

kex.c : additional bounds checks in diffie_sha1/256

---

src/libssh2_priv.h

musl prints `redirecting incorrect #include <sys/poll.h> to <poll.h>`
http://git.musl-libc.org/cgit/musl/commit/include/sys/poll.h?id=54446d730cfb17c5f7bcf57f139458678f5066cc
poll is defined by POSIX to be in poll.h:
http://pubs.opengroup.org/onlinepubs/7908799/xsh/poll.html
---
libssh2 configure does not check which header file provides poll, only that it is present in the libc. I think it is not necessary to add such a check because `poll.h` should work everywhere.

Fix musl build warning on sys/poll.h

---

src/libgcrypt.c

Added calls to gcry_sexp_release to free memory allocated by gcry_sexp_find_token (libgcrypt.c: 396).

Fixed libgcrypt.c memory leak.

---

src/crypto.h
src/hostkey.c
src/openssl.c

 Fix potential typecast error for `_libssh2_ecdsa_key_get_curve_type`

---

src/channel.c

Even though "unexpected error" is vague, it is still more helpful than errno not being set at all.

Make sure the error code is set.

---

src/agent.c

Currently the error details as returned by agent_transact_pageant() are overwritten by a generic "agent list id failed" message by int agent_list_identities(LIBSSH2_AGENT* agent).
The patch fixes that.
PS: I'm not entirely sure if the
```````
LIBSSH2_FREE(agent->session, transctx->response);
transctx->response = NULL;
```````
part is needed, or if these fields are already null upon entering agent_list_identities(). If so, they could be removed, since a failed agent_transact_pageant() doesn't fill them.

Preserve error info from agent_transact_pageant()

---

src/openssl.h

LIBSSH2_ECDSA and LIBSSH2_ED25519 are always defined so the #ifdef
checks would never be false.
This change makes it possible to build libssh2 against OpenSSL built
without EC support.
Change-Id: I0a2f07c2d80178314dcb7d505d1295d19cf15afd

Fix use of ifdef where if should be used

---

src/openssl.c

libssh2's openssl backend has a use-after-free condition if HAVE_OPAQUE_STRUCTS is defined and you call libssh2_init() again after prior initialisation/deinitialisation of libssh2

Fix use-after-free crash in openssl backend

---

src/userauth.c

Caught by ASAN:
```
=================================================================
==73797==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60700001bcf0 at pc 0x00010026198d bp 0x7ffeefbfed30 sp 0x7ffeefbfe4d8
READ of size 69 at 0x60700001bcf0 thread T0
2019-07-04 08:35:30.292502+0200 atos[73890:2639175] examining /Users/USER/*/libssh2_clar [73797]
#0 0x10026198c in wrap_memchr (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x1f98c)
#1 0x1000f8e66 in file_read_publickey userauth.c:633
#2 0x1000f2dc9 in userauth_publickey_fromfile userauth.c:1513
#3 0x1000f2948 in libssh2_userauth_publickey_fromfile_ex userauth.c:1590
#4 0x10000e254 in test_userauth_publickey__ed25519_auth_ok publickey.c:69
#5 0x1000090c3 in clar_run_test clar.c:260
#6 0x1000038f3 in clar_run_suite clar.c:343
#7 …
```

userauth: fix off by one error when loading public keys with no id

---

src/global.c

File: global.c 
Notes: Don't call `libssh2_crypto_exit()` until `_libssh2_initialized` count is down to zero.
Credit: seba30

global.c : fixed call to libssh2_crypto_exit #394

---

src/CMakeLists.txt

I'm not sure why the Visual Studio generators wouldn't do this automatically. I copied what libgit2 is doing.

Generate debug info when building with MSVC

---

acinclude.m4

This is useful for static builds so that the Libs.private field in
libssh2.pc contains correct info for the benefit of pkg-config users.
Static link with libssh2 requires this information.
Signed-off-by: Baruch Siach <baruch@tkos.co.il>
[Retrieved from:
https://git.buildroot.net/buildroot/tree/package/libssh2/0002-acinclude.m4-add-mbedtls-to-LIBS.patch]
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

acinclude.m4: add mbedtls to LIBS

---

src/misc.c

To quiet overly aggressive analyzers.

misc.c: _libssh2_ntohu32 cast bit shifting

---

src/packet.c

file: packet.c
notes:
Use _libssh2_get_string API in SSH_MSG_DEBUG, additional uint32 bounds check in SSH_MSG_GLOBAL_REQUEST

packet.c: improve message parsing

---

src/openssl.c
src/openssl.h

Hi,
for my software FreeFileSync I'm supporting the PuTTY ppk file format, so I'm parsing the pkk files into OpenSSL's EVP_PKEY. Then generate PKIX PEM streams (PEM_write_bio_PrivateKey) in order to inter-op with libssh2 (libssh2_userauth_publickey_frommemory). This works nicely for
ssh-rsa
ssh-dss
ecdsa-sha2-nistp256
ecdsa-sha2-nistp384
ecdsa-sha2-nistp521
key algorithms because libssh2 is using PEM_read_bio_PrivateKey (great!) as an alternative to the openssh key format.
However I've found things do not work well for "ssh-ed25519"
1. _libssh2_pub_priv_keyfile() is missing the code to extract the ed25519 public key from a given private key
2. _libssh2_ed25519_new_private_frommemory is only parsing the openssh key format but does not understand PKIX (as retrieved via …

ssh-ed25519: Support PKIX + calc pubkey from private

---

src/transport.c

Hi,
one of my users is having trouble with crashes in the libssh2 component of my program. The crash is happening inside libssh2_session_handshake() during key exchange:
https://github.com/libssh2/libssh2/blob/f1b6fca89b2c3ca5ea0f47290ad7010d4381bbad/src/transport.c#L768-L779
session->local.comp_abstract is empty, therfore comp_method_zlib_comp() will crash.
To be precise, this is during a second key exchange ("Renegotiating Keys") when compression is active, after a first key exchange had been successful without compression.
The crash can be easily reproduced with the most recent Bitvise 8.37 (https://www.bitvise.com/download-area) when the "delay compression" option is set:
With the patch attached, the crash is apparently avoided, and the SFTP access seems to work as expected, but I'm …

Fix crash with delayed compression (Bitvise 8.37)

---

src/session.c

With gcc 9, libssh2, libcurl and LTO enabled for all binaries I see this
warning (error with -Werror):
vssh/libssh2.c: In function ‘ssh_statemach_act’:
/data/mwrep/rgeissler/ospack/ssh2/BUILD/libssh2-libssh2-03c7c4a/src/session.c:579:9: error: ‘seconds_to_next’ is used uninitialized in this function [-Werror=uninitialized]
579 |     int seconds_to_next;
|         ^
lto1: all warnings being treated as errors
Gcc normally issues -Wuninitialized when it is sure there is a problem,
and -Wmaybe-uninitialized when it's not sure, but it's possible. Here
the compiler seems to have find a real case where this could happen. I
looked in your code and overall it seems you always check if the return
code is non null, not often that it's below zero. I think we should do
the same here. With this patch, …

Fix an LTO -Wundefined warning when mixing with LTO-enabled libcurl.

---

src/openssl.c

In pull request 387 a use-after-free crash in openssl backend was fixed, see https://github.com/libssh2/libssh2/pull/387
I can confirm that this crash also happens in my scenario. 
Pull request 387 was merged into master on 12.Jul 2019. The fix from the pull request fixes the use-after-free bug but also introduces a memory leak as it already has been stated in pull request 413, see https://github.com/libssh2/libssh2/pull/413
I also can confirm this memory leak. Pull request 413 was closed without being merged. When I had a look into it, it basically was a step back to the previous situation, so not a suitable solution.
So, after carefully inspecting the source, I think I understood the original intention of the author of the "#ifdef HAVE_OPAQUE_STRUCTS" blocks and fixed the bug according …

Fix use-after-free crash in openssl backend without memory leak

---

src/agent.c

Hi,
libssh2 currently fails to compile in Visual Studio 16.3.2 for Unicode builds. The attached patch fixes this issue. Other than that libssh2 + pageant works great on Windows.
Best, Zenju

Fix Unicode builds on Windows

---

src/openssl.c

This is a follow up for my pull request #439 ...
With #439 I introduced a "use of uninitialized variable" warning within a code section that is only active if HAVE_OPAQUE_STRUCTS is NOT defined. Here, in my environment HAVE_OPAQUE_STRUCTS is defined ...
The problem is that aes_ctr_cipher.key_len is uninitialized when entering the function for the first time. It also cannot easily be initialized in a "static way". Therefore it cannot be used to determine whether make_ctr_evp still has to be called. Sorry for missing that. This pull request here fixes this now.
Thanks to @tsengjun for reporting this! For some reason I don't understand I only got this comment by email. When looking on https://github.com/libssh2/libssh2/pull/439 this comment doesn't appear.

Fix for use of uninitialized aes_ctr_cipher.key_len

---

Makefile.am

The POSIX comparison operator for test(1) is `=`; bash supports `==` but not even test from GNU coreutils does.

Fix unportable test(1) operator.

---

src/hostkey.c

These types are the same size so most compilers are fine with it, but CodeWarrior (on classic MacOS) throws an ‘illegal implicit conversion’ error

hostkey.c: Fix 'unsigned int'/'uint32_t' mismatch

---

src/os400qc3.h

File: os400qc3.h
Notes: define missing EC types which prevents building
Credit: hjindra

os400qc3.h: define EC types to fix building #426

---

src/os400qc3.h

file: os400qc3.h
notes: fix for modern building of libssh2

os400qc3.h: define sha512 macros

---

docs/HACKING.CRYPTO

This commit updates the HACKING.CRYPTO documentation file in an attempt to make it in sync with current code.
New documented features are:
- SHA384
- SHA512
- ECDSA
- ED25519
Thanks for considering it.

HACKING.CRYPTO: keep up to date with new crypto definitions from code.

---

include/libssh2_sftp.h

Error constants `LIBSSH2_FX_*` are only returned by `libssh2_sftp_last_error()` which returns `unsigned long`. Therefore these constants should be defined as `unsigned long` literals, instead of `int` literals.
Fixes #474

Changed type of LIBSSH2_FX_* constants to unsigned long

---

src/transport.c

malloc(0) may not always return NULL, return error if 'total_num = 0' in _libssh2_transport_read in case of 'payload' will be used later

fix use-of-uninitialized-value

---

src/transport.c

file: transport.c
notes:
moving total_num zero length check from #476 up to the prior bounds check which already includes a total_num check. Makes it slightly more readable.
credit:
Will Cosgrove

transport.c: moving total_num check from #476

---

appveyor.yml

To make it easier to test the WinCNG crypto backend.

appveyor: build and run tests for WinCNG crypto backend

---

src/wincng.c

- wincng: add and improve checks in bit counting function
- wincng: align bits to bytes calculation in all functions
- wincng: do not disable key validation that can be enabled
- wincng: fix return value in _libssh2_dh_secret

Various fixes to the BigNum and DH handling in WinCNG

---

include/libssh2.h

File: libssh2.h
Notes:
Update the min, preferred and max DH group values based on RFC 8270.
Credit:
Will Cosgrove, noted from email list by Mitchell Holland

libssh2.h: Update Diffie Hellman group values

---

.gitignore
.travis.yml
Makefile.am
buildconf
configure.ac
docs/INSTALL_AUTOTOOLS
example/.gitignore
example/Makefile.am

The buildconf script is currently required, because we need to copy a
header around, because it is used both from the library and the examples
sources.
However, having a custom 'buildconf'-like script is not needed if we can
ensure that the header / exists by the time it is needed. For That, we
can just append the src/ directory to the headers search path for the
examples.
And then it means we no longer need to generate the same header twice,
so we remove the second one from configure.ac.
Now, we can just call "autoreconf -fi" to generate the autotools files,
instead of relying on the canned sequence in "buildconf", since
autoreconf has now long known what to do at the correct moment (future
versions of autotools, automake, autopoint, autoheader etc... may
require an other ordering, or …

buildsystem: drop custom buildconf script, rely on autoreconf

---

src/comp.c

Hi,
when libssh2 is compiled with ZLIB support, and ZLIB happens to be compiled with the Z_PREFIX_ macro set, the compress function name (which is a macro) is replaced with "prefix_compress", and comp.c fails to compile:
comp.c(390,23): error C2039: 'wx_zlib_compress': is not a member of 'flags'
In my case the Z_PREFIX_ = "wx_zlib_" is coming from the GUI library (wxWidgets) which is packaging zlib. The attached patch fixes the problem in a minimal way. But if it is still too ugly, maybe the _LIBSSH2_SESSION :: flags :: compress member should be renamed instead?
Best, Zenju

Fix name clash with ZLIB macro "compress"

---

src/transport.c

File: transport.c
Notes:
This is to fix #102, instead of continuing to attempt to read a disconnected socket, it will now error out. 
Credit:
TDi-jonesds

transport.c: socket is disconnected, return error

---

src/crypto.h
src/kex.c
src/openssl.c
src/openssl.h

This cleans up a few things in the curve25519 implementation:
- There is no need to create X509_PUBKEYs or PKCS8_PRIV_KEY_INFOs to
extract key material. EVP_PKEY_get_raw_private_key and
EVP_PKEY_get_raw_public_key work fine.
- libssh2_x25519_ctx was never used (and occasionally mis-typedefed to
libssh2_ed25519_ctx). Remove it. The _libssh2_curve25519_new and
_libssh2_curve25519_gen_k interfaces use the bytes. Note, if it needs
to be added back, there is no need to roundtrip through
EVP_PKEY_new_raw_private_key. EVP_PKEY_keygen already generated an
EVP_PKEY.
- Add some missing error checks.
NB: I was able to check this compiled, but it looks like the tests requires some docker setup. So probably wait for the CI to clear here.

openssl: clean up curve25519 code

---

.travis.yml
src/mbedtls.c
src/mbedtls.h

This PR adds support for `ECDSA` for both key exchange and host key algorithms.
The following elliptic curves are supported:
- 256-bit curve defined by FIPS 186-4 and SEC1
- 384-bit curve defined by FIPS 186-4 and SEC1
- 521-bit curve defined by FIPS 186-4 and SEC1

ECDSA support for mbed TLS

---

.travis.yml
configure.ac
tests/Makefile.am
tests/ossfuzz/.gitignore
tests/ossfuzz/Makefile.am
tests/ossfuzz/ossfuzz.sh
tests/ossfuzz/ssh2_client_fuzzer.cc
tests/ossfuzz/standaloneengine.cc
tests/ossfuzz/testinput.h
tests/ossfuzz/travisoss.sh

This adds support for an OSS-Fuzz fuzzing target in ssh2_client_fuzzer,
which is a cut down example of ssh2.c. Future enhancements can improve
coverage.
---
I've tested this with the oss-fuzz framework and it appears to find repeated READ access bugs in one particular function, so I think it's definitely worth getting in!

Add support for an OSS Fuzzer fuzzing target

---

src/agent.c

**Describe the bug**
libssh2 functions return error [LIBSSH2_ERROR_AGENT_PROTOCOL](https://github.com/libssh2/libssh2/blob/master/include/libssh2.h#L499) for valid client-server protocol.
Reason: posix functions `recv()`/`send()` accept buffer_start_pointer and buffer_len. Theese functions return succeed len which could be less then buffer_len. libssh2 doesn't cover this case ( [1](https://github.com/libssh2/libssh2/blob/master/src/agent.c#L187), [2](https://github.com/libssh2/libssh2/blob/master/src/libssh2_priv.h#L198) ): so only part of message could be finished.
It leads to operations with garbage at the end of buffer on `recv()`.
For example in [agent_list_identities()](https://github.com/libssh2/libssh2/blob/master/src/agent.c#L498) in my project:
```
=== agent_list_identities got …
```

Recv and send all bytes via network

---

src/CMakeLists.txt

Files:
CMakeLists.txt
Notes:
Use CMAKE_INSTALL_LIBDIR directory
Credit: Arfrever

CMakeLists.txt: respect install lib dir #405

---

src/session.c

Seems the author intend to terminate "banner_dup" buffer, later print to the debug console.

Correct typo which may lead to stack overflow

---

src/kex.c

There is a small typo in src/kex.c.
Should read `number` rather than `niumber`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, niumber -> number

---

src/kex.c

File: kex.c
Notes:
Moved the macro LIBSSH2_KEX_METHOD_EC_SHA_HASH_CREATE_VERIFY outside of the LIBSSH2_ECDSA since it's also now used by the ED25519 code.
Sha 256, 384 and 512 need to be defined for all backends now even if they aren't used directly. I believe this is already the case, but just a heads up.
Credit:
Stefan-Ghinea

kex.c: move EC macro outside of if check #549

---

src/kex.c

file: kex.c
notes:
use string_buf in ecdh_sha2_nistp() to avoid attempting to parse malformed data

kex.c: use string_buf in ecdh_sha2_nistp

---

src/kex.c

file: kex.c
notes: if haystack isn't null terminated we should use memchr() not strchar(). We should also make sure we don't walk off the end of the buffer.
credit: 
Will Cosgrove, reviewed by Michael Buckley

kex.c: kex_agree_instr() improve string reading

---

tests/ossfuzz/ssh2_client_fuzzer.cc

file: ssh_client_fuzzer.cc
notes: the session needs blocking mode turned on to avoid EAGAIN being returned from libssh2_session_handshake()
credit:
Will Cosgrove, reviewed by Michael Buckley

ssh_client_fuzzer.cc: set blocking mode on

---

src/transport.c

file: transport.c
notes: If the payload is invalid and there is an early return, we could leak the payload
credit:
Will Cosgrove

transport.c: release payload on error

---

src/bcrypt_pbkdf.c

blf_enc() takes a number of 64-bit blocks to encrypt, but using sizeof(uint64_t) in the calculation triggers a warning with clang 10 because the actual data type is uint32_t. Pass BCRYPT_BLOCKS / 2 for the number of blocks like libc bcrypt(3) does.
Ref: https://github.com/openbsd/src/commit/04a2240bd8f465bcae6b595d912af3e2965856de
Fixes #562
Closes #xxx

blowfish: fix clang10 false positive warning

---

tests/test_public_key_auth_succeeds_with_correct_ed25519_key_from_mem.c

Hello,
This PR fixes:
```
/home/ubuntu/opensource/libssh2/tests/test_public_key_auth_succeeds_with_correct_ed25519_key_from_mem.c: In function ‘test’:
/home/ubuntu/opensource/libssh2/tests/test_public_key_auth_succeeds_with_correct_ed25519_key_from_mem.c:16:11: warning: unused variable ‘fp’ [-Wunused-variable]
16 |     FILE *fp = NULL;
|           ^~
/home/ubuntu/opensource/libssh2/tests/test_public_key_auth_succeeds_with_correct_ed25519_key_from_mem.c: In function ‘read_file’:
/home/ubuntu/opensource/libssh2/tests/test_public_key_auth_succeeds_with_correct_ed25519_key_from_mem.c:56:9: warning: unused variable ‘rc’ [-Wunused-variable]
56 |     int rc;
|         ^~
```

Fix unused variables warning

---

src/libssh2_priv.h

Some toolchains like devkitPro's 3DS toolchain don't have iovec defined for whatever reason... This fixes that. I'm not entirely sure how the iovecs are being used since I don't see any calls to writev or readv, but this at least allows it to compile for the system.

libssh2_priv.h: add iovec on 3ds

---

.github/workflows/ci.yml
.travis.yml
ci/ossfuzz.sh
tests/ossfuzz/ossfuzz.sh

I saw in the mailing list that there was some desire to move from Travis (and maybe Appveyor) to Github Actions. I also wanted to do this in the hope that it will cut down CI times and spurious CI failures that I have seen over and over.
To have the workflows I've added run for this PR, I believe a maintainer will need to approve the workflow for this PR because I am not yet marked as a contributor.
https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks
In testing I've seen Linux builds ~8 minutes in length.
Notes:
- `ubuntu-16.04` was selected as the virtual environment to run on as this matches what Travis has been using.
- For 32 builds, `zlib1g-dev:i386` needed to be installed for whatever reason. I'm guessing this was installed by the …

ci: Swap from Travis to Github Actions

---

.github/workflows/ci.yml

It looks like the $default-branch macro only works in templates, not
workflows. This is not explicitly stated anywhere except the linked PR
comment.
https://github.com/actions/starter-workflows/pull/590#issuecomment-672360634

Explicitly state the default branch it GitHub Action CI

---

tests/openssh_fixture.c

If reading the full output from the executed command took multiple
passes (such as when reading multiple lines) the old code would read
into the buffer starting at the some position (the start) every time.
The old code only works if fgets updated p or had an offset parameter,
both of which are not true.

tests: Fix potential overwrite of buffer when reading stdout of command

---

src/openssl.c

Hello,
We discovered that bug when we linked curl with openssl version 3. It has been reported in #463. 
I propose this fix.
Regards,

Fix EVP_Cipher interface change in openssl 3

---

src/openssl.c

Avoid initing MD5 digest, which is not permitted in OpenSSL FIPS certified cryptography mode.
Fixes: https://github.com/libssh2/libssh2/issues/527

Avoid OpenSSL latent error in FIPS mode

---

src/userauth.c

file: userauth.c
notes: libssh2 now supports many other key types besides RSA, if the library is built without RSA support and a user attempts key auth it shouldn't be an automatic error.
credit: 
Will Cosgrove

userauth.c: don't error if using keys without RSA

---

.github/workflows/ci.yml
.travis.yml

The OpenSSH server docker image used for tests is pre-built to prevent
wasting time building it during a test, and unneeded rebuilds are
prevented by caching the image layers.

ci: Speed up docker builds for tests

---

src/openssl.c
src/pem.c
src/userauth.c

Hi,
_libssh2_pub_priv_keyfilememory in src\openssl.c already sets _libssh2_error() with detailed error messages, while its caller, src\userauth.c, userauth_publickey_frommemory() overwrites it with a generic "Unable to extract public key from private key."
The patch fixes this to facilitate troubleshooting userauth_publickey_frommemory issues.
Best

Fix detailed _libssh2_error being overwritten

---

src/packet.c

File:
packet.c
Notes:
Attempt keyboard interactive login (Azure AD 2FA login) and use more than 60 seconds to complete the login, the connection fails.
The _libssh2_packet_require function does almost the same as _libssh2_packet_requirev but this function sets state->start = 0 before returning.
Credit:
teottin, Co-authored-by: Tor Erik Ottinsen <tor.ottinsen@kdi.kongsberg.com>

packet.c: Reset read timeout after received a packet (#576)

---

tests/Makefile.am

Hello,
With the latest [tarball](https://libssh2.org/snapshots/libssh2-1.9.0-20210518.tar.gz), I have these tests failure.
```
The following tests FAILED:
8 - test_public_key_auth_succeeds_with_correct_encrypted_rsa_key (Failed)
12 - test_public_key_auth_succeeds_with_correct_rsa_openssh_key (Failed)
```
This is raised by:
```
libssh2_userauth_publickey_fromfile_ex failed (-16): Unable to open public key file
```
I added the missing client keys and now all the tests work.
Regards,

Add missing tests client keys in distribution tarball

---

configure.ac

To get this script to run with Autoconf 2.71 on macOS I had to remove the undefine of the backend for loop variable. It seems scoped to the for loop and also isn't referenced later in the script so it seems OK to remove it.

configure.ac: don't undefine scoped variable

---

src/openssl.c

Notes:
FIPS_mode() is not implemented in LibreSSL, removed in OpenSSL 3.0 and introduced in 0.9.7. Added guards around making this call.
Credit:
Will Cosgrove

openssl.c: guards around calling FIPS_mode() #596

---

tests/openssh_fixture.c

Hello,
I propose to automatically remove the openssh_server containers on test exit. The reason is that we often don't have access to the CI/CD system to manually purge all the exited containers.

[tests] Remove openssh_server container on test exit

---

tests/Makefile.am

Hello,
I just spot that building and running the tests (CMake build) some keys are missing in the release tarball:
```
Start 17: test_public_key_auth_succeeds_with_correct_signed_ecdsa_key
17/19 Test #17: test_public_key_auth_succeeds_with_correct_signed_ecdsa_key ........***Failed    1.36 sec
libssh2_userauth_publickey_fromfile_ex failed (-16): Unable to open public key file
```
Regards,

[1.10.0] Add missing key in case openssl > 1.1.0

---

tests/openssh_fixture.c

File: openssh_fixture.c
Notes:
Fix `portable_sleep` return type warning
Credit:
Will Cosgrove

openssh_fixture.c: fix warning

---

tests/openssh_fixture.c

Ok following #616, instead of increasing the buffer for an output we don't care (output of the docker build), let's just stop logging the whole image construction. We will still get the error message if any.
Don't hesitate to tell me if you prefer something else.

Fix openssh_server build not working (#616)

---

src/hostkey.c

File: hostkey.c
Notes:
Additional key length checking before calling _libssh2_ed25519_new_public()
Credit:
Will Cosgrove

hostkey_method_ssh_ed25519_init() check key bounds

---

src/userauth.c

... before using it.
Reported-by: MarcoPoloPie
Fixes #649

userauth: check for too large userauth_kybd_auth_name_len

---

docs/HACKING-CRYPTO
docs/libssh2_session_methods.3
include/libssh2.h
src/crypto.h
src/hostkey.c
src/kex.c
src/libgcrypt.c
src/libgcrypt.h
src/libssh2_priv.h
src/mbedtls.c
src/mbedtls.h
src/openssl.c
src/openssl.h
src/os400qc3.c
src/os400qc3.h
src/packet.c
src/userauth.c
src/wincng.c
src/wincng.h

Files: openssl.h, openssl.c, crypto.h, hostkey.c, HACKING-CRYPTO
Notes:
Added rsa-sha2-256 and rsa-sha2-512 as described in RFC 8332 to OpenSSL backend. To implement in other backends implementers need to define LIBSSH2_RSA_SHA2 and implement _libssh2_rsa_sha2_sign and _libssh2_rsa_sha2_verify.
Credit:
Will Cosgrove

RSA SHA2 256/512 key upgrade support libssh2 #536

---

Makefile.wolfSSL.inc
acinclude.m4
configure.ac
src/Makefile.am
src/crypto.h
src/openssl.c
src/openssl.h

It uses wolfSSL's OpenSSL compatibility layer, so rather than introduce new
wolfssl.h/c files, the new backend just reuses openssl.h/c. Additionally,
replace EVP_Cipher() calls with EVP_CipherUpdate(), since EVP_Cipher() is not
recommended.

Add support for a wolfSSL crypto backend.

---

src/userauth.c

Some code was recently changed from using memmem to memcmp, a good change, but memmem returns non-NULL on a match, whereas memcmp returns 0 on a match, so the return value has to be checked in the opposite way.
The code affected could result in a failure to authenticte, depending on which public key accepted algorithms the server supports. This is unlikely to happen in practice, as most servers support enough algorithms that even after incorrectly filtering out some algorithms, some options will remain.

Fix a couple errors in code that was changed from memmem to memcmp

---

include/libssh2.h
src/agent.c
src/userauth.c

Files: libssh2.h, agent.c, userauth.c
Notes:
Part 2 of the fix for #659. This adds rsa key downgrading for agents that don't support sha2 upgrading. It also adds better trace output for debugging/logging around key upgrading.
Credit:
Will Cosgrove (signed off by Michael Buckley)

Legacy Agent support for rsa2 key upgrading/downgrading #659

---

src/session.c

Missed freeing `server_sign_algorithms` and `sign_algo_prefs` when porting over rsa2 additions.

free RSA2 memory

---

src/libssh2_priv.h
src/packet.c

When allocating `session->server_sign_algorithms` which is a `char*` is is important to also allocate space for the string-terminating null byte at the end and make sure the string is actually null terminated.
Without this fix, the `strchr()` call inside the `_libssh2_key_sign_algorithm` (line 1219) function will try to parse the string and go out of buffer on the last invocation.
EDIT:
Dunno why i didn't directly just link to the bug lol.
Heap buffer overflow (without this fix) happens here https://github.com/libssh2/libssh2/blob/de7a74aff24c47b2f2e9815f0a98598195d602e4/src/userauth.c#L1212-L1219

Fix heap buffer overflow in _libssh2_key_sign_algorithm

---

docs/libssh2_userauth_keyboard_interactive_ex.3
docs/libssh2_userauth_password_ex.3

I noticed a typo in the manual page [libssh2_userauth_keyboard_interactive_ex](https://www.libssh2.org/libssh2_userauth_keyboard_interactive_ex.html)  in the ERRORS section. There is  a `f` before `LIBSSH2_ERROR_AUTHENTICATION_FAILED`.
The other errors are displayed in italic.
This pull request will fix that issue.

Fix typos in manual page

---

src/CMakeLists.txt

Reverts libssh2/libssh2#547; this doesn't build clean anymore with the keyboard interactive changes.

Revert "Option to build both static and shared libraries"

---

src/mbedtls.c
src/mbedtls.h

Should fix https://github.com/libssh2/libssh2/issues/687.
I basically did some pattern matching from https://github.com/libssh2/libssh2/commit/64a555d6f5aafed504a10e5b756e85c91b1d56ce. I'm not familiar with the libssh2 codebase so please do tell if there is something to be changed.

Add RSA-SHA2 support for the mbedtls backend

---

src/openssl.h

In openssl 1.1.0 and later openssl decided to change some of the defines used to check if certain features are not compiled in the libraries.
The particular changes that caused the problem libssh2 are:
> - OPENSSL_NO_EC{DH,DSA} merged into OPENSSL_NO_EC
> - OPENSSL_NO_RIPEMD160, OPENSSL_NO_RIPEMD merged into OPENSSL_NO_RMD160
Needless to say, any code that depended on the old defines broke as a consequence. This is my proposed fix for libssh2.

Fix build since openssl 1.1.0 when ECDSA and/or RIPEMD are disabled

---

src/userauth.c

Hi,
this patch fixes application crashes due to heap corruption. Turns out the null terminator is written one byte outside of the allocated area.
Regards, Zenju

Fix buffer overflow while receiving SSH_MSG_USERAUTH_BANNER

---

src/openssl.h

LibreSSL 3.5.0 made more structures opaque, so let's enable existing
support for that when building against these LibreSSL versions.
Ref: https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.5.0-relnotes.txt

openssl: add support for LibreSSL 3.5.x

---

docs/libssh2_channel_flush_ex.3

In https://github.com/libssh2/libssh2/issues/614 it was identified the docs do not accurately show how libssh2_channel_flush_ex() return value is set. I have updated the doc's to correctly show what the function is returning.

Fixing description of libssh2_channel_flush_ex() in docs

---

src/blf.h
src/blowfish.c

Originally driven by https://github.com/pyca/bcrypt/issues/169, OpenBSD removed Niels Provos's BSD advertisement clause in version 7.1:
https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/sys/lib/libsa/blowfish.c.diff?r1=1.1&r2=1.2
https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/sys/lib/libsa/blowfish.h.diff?r1=1.1&r2=1.2
This enables using libssh2 in GPL software.

Drop advertisement clause on Blowfish

---

src/sftp.c

LIBSSH2_ERROR_BUFFER_TOO_SMALL is returned if the buffer is too small to contain a returned directory entry. On this condition we jump to the label `end`. At this point the number of names left is decremented despite no name being returned.
As suggested in #714, this commit moves the error label after the decrement of `names_left`.
Fixes #714

sftp: Prevent files from being skipped if the output buffer is too small

---

src/wincng.c
src/wincng.h

Added code to support RSA-SHA2 for WinCNG backend. It seems to work fine here. Let me know if this is okay.

Add RSA-SHA2 support for the WinCNG backend

---

src/CMakeLists.txt

https://aur.archlinux.org/packages/mingw-w64-libssh2
https://cmake.org/cmake/help/latest/prop_tgt/IMPORT_PREFIX.html

Fix DLL import library name

---

win32/GNUmakefile

via `export MBEDTLS_PATH=<mbedtls-root>`.

win32/GNUmakefile: add mbedTLS support

---

.github/workflows/ci.yml
src/mbedtls.c
src/mbedtls.h

Make libssh2 compile cleanly with mbedTLS 3.x and later.
This patch makes use of `MBEDTLS_PRIVATE()`, which is not the
recommended, future-proof way to access mbedTLS data structures. This
method may break with a minor upgrade, according to the authors. This
is also the method used by libcurl.
Also:
- Fix a potentially uninitialized variable in
`libssh2_mbedtls_rsa_sha2_sign()`. This happened in an error path,
resulting in an unnecessary mbedTLS API call, with an uninitialized
`md_type`.
- Bump mbedTLS version used in CI tests to 3.2.1.
- Delete unnecessary CAST5 mapping (to null-cipher) from the
mbedTLS header.
Fixes #751
---
Migrated to separate PRs:
- a way to enable detailed logging in tests. [→ #761]
- run tests without docker. [→ #762]
It will need more work to make it actually …

add mbedTLS 3.x support

---

src/mbedtls.c

Fixes comparison with the result value coming from `mbedtls_rsa_pkcs1_verify`. Success is 0, not 1. Fixes #758

Fix regression with rsa_sha2_verify #758

---

src/channel.c
src/session.c

Hi,
some callers of _libssh2_packet_requirev() fail to set _libssh2_error(). This creates the situation where e.g. libssh2_session_handshake() fails, but libssh2_session_last_error() confusingly returns LIBSSH2_ERROR_NONE.
Best, Zenju

Fixed error handling of _libssh2_packet_requirev callers

---

src/session.c

Skip leading \r and \n characters in banner_receive()

---

src/crypt.c

This make it more likely that a stronger one will be negotiated rather
than a weaker variant.

Reorder AES crypt methods so stronger ones are first

---

src/openssl.h

For now disable OpenSSL 3 warnings for clean builds.

Disable deprecated warnings for OpenSSL 3 #805

---

CMakeLists.txt
src/CMakeLists.txt

I mistakenly pruned some non-Windows logic, also missing the fact that
our local `check_function_exists_may_need_library()` set the `NEED_*`
variables. Oddly, only `src` imported this function, yet also `examples`
and `tests` called it indirectly. The referenced `HAVE_SOCKET` /
`HAVE_INET_ADDR` variables might be coming from an upstream CMake
project? Leaving those there also, just in case.
Regression from 31fb8860dbaae3e0b7d38f2a647ee527b4b2a95f

cmake: restore non-Windows socket lib detection

---

src/CMakeLists.txt

Add OpenSSL 3 and versionless DLL names. Also modernize warning messages and variable names.
Do we need the OpenSSL-Windows-specific check and the related `RUNTIME_DEPENDENCIES` feature? The list of OpenSSL DLLs was out of date for 1.5 years without anybody noticing. Keeping it fresh is a chore and copying around DLL dependencies rarely helps as much as expected. This check also results in unuseful warnings in certain build scenarios, e.g. when linking to OpenSSL statically.

cmake: update openssl dll list

---

CMakeLists.txt
src/CMakeLists.txt

Based on patch by Christian Beier:
When building libssh2 and the libraries it depends on from source
using a single CMakeLists.txt (as is common on Android), libssh2's
CMake has to be hinted at where to find other libs by setting
variables like OPENSSL_SSL_LIBRARY and so on.
Now, as under Android there's one single CMakeLists.txt that has to
`add_subdirectory()` all other CMakeLists.txt, there's only one
configure phase and one build phase. That means when libssh2 is
configured, the libs it is configured to use are actually not built
yet.
In this case it's a problem to use the libs in LIBRARIES when checking
for nonblocking sockets as some libs in there are not yet built,
failing the test and ending up with HAVE_DISABLED_NONBLOCKING in
libssh2_config.h.
Fix this by using a separate, clean …

cmake: use only socket libs when checking non-blocking sockets

---

src/libssh2_priv.h

E.g.:
`channel.c(370): warning C4127: conditional expression is constant`
Ref:
https://ci.appveyor.com/project/libssh2org/libssh2/builds/46437333/job/5rak1vcl9hue31ei#L190

build: silence bogus C4127 warnings with MSVS 2013 and earlier

---

src/CMakeLists.txt

This re-syncs the list of compiled objects in cmake builds with non-cmake builds.
Follow-up to 16619a8eddec35bb8582d1c334db0fc13b0817c4.

cmake: add os400qc3.c to SOURCES

---

src/libssh2_priv.h

autotools builds already did auto-detect and set this mingw-specific macro, but CMake and GNU Make builds did not. This patch fixes that.
Necessary for `src/scp.c`.

build: set _FILE_OFFSET_BITS=64 for mingw-w64

---

src/libssh2_priv.h

Should fix these warnings with MSVS 2013 and older:
`agent.c(294): warning C4013: '_libssh2_snprintf' undefined; assuming extern returning int`
Follow-up to 4cdf785cd313c3272d04c2ef7458a35d44533d8b.

snprintf: add missing prototype for local replacement

---

src/misc.h

Regression from a0e424a51c27cc27af611ba20d134f9a9ae35273
Fixes #824

fix compiling with LIBSSH2_NO_CLEAR_MEMORY and OpenSSL

---

CMakeLists.txt
example/CMakeLists.txt
src/CMakeLists.txt
tests/CMakeLists.txt

This restores socket libs to their pre-regression positions.
Without this, `ld` doesn't find `ws2_32` symbols when referenced from TLS libs.
Regression from 31fb8860dbaae3e0b7d38f2a647ee527b4b2a95f

cmake: reposition `ws2_32` to make binutils `ld` work again

---

CMakeLists.txt

Added in cf80f2f4b5255cc85a04ee43b27a29c678c1edb1 (on 2016-08-14), with the title "Basic dockerised test suite".
It's not clear why a C standard was explicitly set, but a side-effect of this is that CMake-built binaries diverged from ones built with autotools or GNU Make (using the same compiler and configuration).
Another issue is that this may introduce ABI incompatibility with binaries built with a different C standard flag, e.g. the C compiler default or one used for other components of a final app.
Seems unlikely, but if our tests require this option, we should set it for the CI builds only?

cmake: unset forced CMAKE_C_STANDARD 90

---

tests/CMakeLists.txt
tests/libssh2_config_cmake.h.in

Turns out `test_keyboard_interactive_auth_info_request.c` requires `src/libssh2_priv.h`, which in turn requires a correctly set `HAVE_SNPRINTF`.
Follow-up to 4cdf785cd313c3272d04c2ef7458a35d44533d8b.

cmake: detect HAVE_SNPRINTF for tests

---

tests/CMakeLists.txt
tests/Makefile.am
tests/test_warmup.c

Flakiness got continously worse these last days. It didn't seem related to recent commits. Flakiness also picked up in GitHub CI runs, something rarely seen before. Manual restart consistently fixed them.
The repeating pattern was the _first_ test (`test_hostkey`) failing, with `libssh2_session_handshake failed (-13): Failed getting banner`. Failures came after a lengthy wait, suggesting a timeout.
I then reversed the order of the first two tests, and it turned out that the _first_ test failed again (`test_hostkey_hash`). Also pointing to a timeout issue.
Then I added a dummy test to "warm up" whatever needs warming up in the layers of CI + Docker + ssh server and their interconnects. This helped, and GitHub CI tests run without failure right for the first time. AppVeyor CI also improved …

tests: workaround for intermittent first test failures

---

docs/INSTALL_CMAKE.md
src/CMakeLists.txt
tests/CMakeLists.txt

wolfSSL supports building with zlib as a dependency, that's the reason for the ZLIB logic in the patch.
Also add it to `docs/INSTALL_CMAKE.md` and to the help text in `src/CMakeLists.txt`.
Running tests not actually tested.
Follow-up to 9f217a17f6f3c2047c4a1668a5c037a75a02abfd
Ref: #817

cmake: add wolfSSL support to tests

---

appveyor.yml

Trying to mitigate occasional intermittent failures while installing docker.
Ref: https://ci.appveyor.com/project/libssh2org/libssh2/builds/46460704/job/g3t7bro6ta6n3pk6#L52

ci: retry choco install on appveyor

---

src/agent.c
src/channel.c
src/comp.c
src/hostkey.c
src/kex.c
src/libssh2_priv.h
src/misc.c
src/openssl.c
src/packet.c
src/publickey.c
src/scp.c
src/session.c
src/sftp.c
src/transport.c
src/userauth.c

Before this patch, with debug logging disabled, libssh2 code used a
variadic macro to catch `_libssh2_debug()` calls, and convert them to
no-ops. In certain conditions, it used an empty inline function instead.
Variadic macro is a C99 feature. It means that depending on compiler,
and build settings, it littered the build log with warnings about this.
The new solution uses the trick of passing the variable arg list as a
single argument and pass that down to the debug function with a regular
macro. When disabled, another regular C89-compatible macro converts it
to a no-op.
This makes inlining, C99 variadic macros and maintaining the conditions
for each unnecessary and also makes the codebase compile more
consistently, e.g. with forced C standards and/or picky warnings.
TL;DR: It makes this …

src: C89-compliant _libssh2_debug() macro

---

src/wincng.c

wincng: fix memory leak in libssh2_dh_key_pair()

---

win32/libssh2_config.h

As in curl:
https://github.com/curl/curl/blob/7fa6e36583b52dd8f1e639b370c9a2849be81b54/lib/config-win32.h#L221

win32: set HAVE_STRTOLL with MSVS 2013 and newer

---

docs/INSTALL_AUTOTOOLS

The "convenience script" mentioned in the file is the "buildconf" file, which is no longer recommended.

Update instructions for building with Autotools

---

.github/workflows/ci.yml
appveyor.yml

With CMake builds supporting static-shared libssh2 builds in a single pass, we no longer need to run static and shared jobs separately. For the same effect it's enough to run builds with both shared and static builds enabled. Halving CI jobs.
We add an extra run to test the CMake config-path without shared builds enabled.
This allows to add useful jobs, e.g. MSVS 2022 or ZLIB-enabled builds for Windows, valgrind builds or other useful stuff, without stretching CI run times further.
Ref: #863
Closes #865

ci: use static+shared builds to cut number of cmake jobs

---

src/CMakeLists.txt

To allow more flexibility when defining targets.

cmake/src: move build options before target definitions

---

CMakeLists.txt

Regression from 4e2580628dd1f8dc51ac65ac747ebcf0e93fa3d1

cmake: fix error with static lib off and example/tests on

---

appveyor.yml

- limit static-only build to a single platform (x64).
- skip running ctest for the static-only build.
- use MSVS 2013 for static-only builds. It's faster.
- run static-only test before WinCNG ones. Otherwise it's often skipped
due to WinCNG failures (#804).

ci: speed up static-only build tests on AppVeyor

---

appveyor.yml

Was: v1.0.2.
Keep using v1.0.2 with the static-only test. To make sure we don't break support.

ci: test with OpenSSL v1.1.1 on AppVeyor

---

src/CMakeLists.txt

Before this patch, cmake did a single compilation pass when we enabled
both shared and static lib targets. This saves build time (esp. with
MinGW targets and cross-compiling), but has the disadvantage that static
libs built this way must have PIC enabled (offering slightly less
performance) and `dllexport` enabled also, which means that executables
linking the static libssh2 lib export its public symbols.
To avoid these downsides, this patch separates the two passes and
creates a non-PIC, non-`dllexport` static lib, even when also building
the shared lib.
---
One fallout of the new method is duplicate compiler warnings. Here
the solution is to not have any warnings. See #846.

cmake: separate compilation passes for shared/static

---

.github/workflows/ci.yml
appveyor.yml

Consider warnings as errors for CMake jobs in CI.
Cherry-picked from #846
Closes #877
---
TODO:

ci: cmake `ENABLE_WERROR` -> `ON`

---

src/libssh2_priv.h

`#undef snprintf` before redefining it, when `HAVE_SNPRINTF` is not defined, even though `snprintf` is available and it should have been. Possibly with 3rd party builds.
Downside is that cases of missing `HAVE_SNPRINTF` are less trivially detected at compile-time.
Closes #881

src: more tolerant snprintf() local override

---

configure.ac
docs/INSTALL_AUTOTOOLS
docs/INSTALL_CMAKE.md
nw/GNUmakefile
os400/libssh2_config.h
src/CMakeLists.txt
src/kex.c
vms/libssh2_config.h
win32/libssh2_config.h

libssh2 supports an "old" style KEX message
`SSH2_MSG_KEX_DH_GEX_REQUEST_OLD`, as an off-by-default build option.
OpenSSH deprecated/disabled this feature in v6.9 (2015-07-01):
https://www.openssh.com/releasenotes.html#6.9
This patch deletes this obsolete feature from libssh2, with no option
to enable it.
Added to libssh2 in: cf8ca63ea0c9388c8ae9079961d7e6a91b72b5c8 (2004-12-31)
RFC: https://datatracker.ietf.org/doc/html/rfc4419 (2006-03)
Closes #872

delete legacy SSH2_MSG_KEX_DH_GEX_REQUEST_OLD build option

---

configure.ac
os400/libssh2_config.h
src/CMakeLists.txt
src/crypt.c
src/mac.c

Null-cipher and null-MAC are security footguns we want to avoid.
Existing option names to toggle these were ambiguous and gave room for
misinterpretation. Some projects may have had these options enabled by
accident.
This patch aims to make it more difficult to enable them, and making
sure that existing methods require an update to stay enabled.
- delete CMake/autotools settings to enable the "none" cipher and MAC.
- rename existing C macros that can enable them.
To use them, pass them as custom `CPPFLAGS` to the build.
- enable them only if `LIBSSH2DEBUG` is also enabled.
Best would be to delete them, though they may have some use while
developing libssh2 itself, or debugging.
Closes #873

rework how to enable insecure null-cipher/null-MAC

---

.github/workflows/ci.yml
appveyor.yml

`--parallel 2` did not seem to make builds faster. Neither did 4 or 6.
Delete this option from both GHA and AppVeyor jobs.
On AppVeyor, with VS, it uses MSBuild under the hood where apparently
`--parallel` doesn't help [1]. The suggested MSBuild-specific option
`/p:CL_MPcount=2` did not improve build times either.
CMake spends significant time (comparable to building the project
itself) on feature detection, it'd be nice to execute those in parallel,
but I found not such CMake option.
[1] https://discourse.cmake.org/t/parallel-does-not-really-enable-parallel-compiles-with-msbuild/964
Partial revert of 7a039d9a7a2945c10b4622f38eeed21ba6b4ec55

ci: drop cmake --parallel

---

NMakefile
ci/checksrc.pl
ci/checksrc.sh
example/ssh2.c
example/x11.c
src/NMakefile
src/hostkey.c
src/kex.c
src/mbedtls.c
src/misc.c
src/misc.h
src/openssl.c
src/os400qc3.c
src/scp.c
src/session.c
tests/test_keyboard_interactive_auth_info_request.c

Update from:
https://github.com/curl/curl/blob/5fec927374e4d9553205d861f2dcb39ec78002cc/scripts/checksrc.pl
- suppress these new checks:
- EQUALSNULL: 320 warnings
- NOTEQUALSZERO: 142 warnings
- TYPEDEFSTRUCT: 16 warnings
We can enabled them in the future.
- fix all other new ones.
- also fix whitespace in two `NMakefile` files.

checksrc: update and fix warnings

---

win32/GNUmakefile

Follow-up to b8762c1003d97e109efa587bdc760ff9873949eb

GNUmakefile: minor fix for DYN mode [ci skip]

---

src/openssl.h

It's `int` in wolfSSL. `size_t` in OpenSSL/quictls/LibreSSL/BoringSSL.
Ref: https://github.com/wolfSSL/wolfssl/blob/ba47562d182e10e59813da012e0ab8ef20892231/wolfssl/openssl/hmac.h#L60-L61
/cc @wolfSSL
---
```
../src/mac.c -o release/mac.o
In file included from ../src/crypto.h:42,
from ../src/libssh2_priv.h:165,
from ../src/mac.c:38:
../src/mac.c: In function 'mac_method_hmac_sha2_512_hash':
../src/mac.c:120:38: warning: conversion from 'size_t' {aka 'long long unsigned int'} to 'int' may change value [-Wconversion]
120 |     libssh2_hmac_update(ctx, packet, packet_len);
|                                      ^~~~~~~~~~
../src/openssl.h:319:26: note: in definition of macro 'libssh2_hmac_update'
319 |   HMAC_Update(ctx, data, datalen)
|                          ^~~~~~~
../src/mac.c:122:41: …
```

wolfssl: add workaround for HMAC_Update() len arg difference

---

src/session.c

```
src/session.c:675:52: warning: implicit conversion loses integer precision: 'long' to '__darwin_suseconds_t' (aka 'int') [-Wshorten-64-to-32]
tv.tv_usec = (ms_to_next - tv.tv_sec*1000) * 1000;
~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
```

src: fix compiler warning on Darwin

---

appveyor.yml

This results in better job names (now including CPU), avoiding the
complex exception rules, and fine-tuning the order and variation of
these tests.
Enable `LIBSSH2DEBUG` for two of the existing jobs.

ci: flatten AppVeyor jobs, add debug builds

---

src/libssh2_config_cmake.h.in

- `HAVE_MEMSET_S` missing since 03092292597ac601c3f9f0c267ecb145dda75e4e (2018-08-02)
- `HAVE_EXPLICIT_BZERO` and `HAVE_EXPLICIT_MEMSET` missing since 00005682f7b9a1aa42be50e269056ea873637047 (2023-03-28)

cmake: add missing #cmakedefines to src

---

CMakeLists.txt
configure.ac
os400/libssh2_config.h
src/libssh2_config_cmake.h.in
src/libssh2_priv.h

It was used once in `src/libssh2_priv.h`, but without any effect. The header included `ws2tcpip.h` twice, once guarded by `HAVE_WS2TCPIP_H` and another time by `HAVE_WINSOCK2_H`.
Dedupe these to not use `HAVE_WS2TCPIP_H`. Then delete detection of this feature from all build methods.
TODO: Replace `HAVE_WINSOCK2_H` with `_WIN32`/`WIN32`.

delete redundant `HAVE_WS2TCPIP_H`

---

CMakeLists.txt

This gives a chance to auto-detect mbedTLS on Windows with CMake.

cmake: detect WinCNG last

---

CMakeLists.txt
acinclude.m4
configure.ac
example/scp.c
example/scp_nonblock.c
example/scp_write.c
example/scp_write_nonblock.c
example/sftp.c
example/sftp_RW_nonblock.c
example/sftp_append.c
example/sftp_mkdir.c
example/sftp_mkdir_nonblock.c
example/sftp_nonblock.c
example/sftp_write.c
example/sftp_write_nonblock.c
example/sftp_write_sliding.c
example/sftpdir.c
example/sftpdir_nonblock.c
example/ssh2.c
example/ssh2_agent.c
example/ssh2_agent_forwarding.c
example/ssh2_echo.c
example/ssh2_exec.c
os400/libssh2_config.h
src/libssh2_config_cmake.h.in
src/libssh2_priv.h
tests/openssh_fixture.c
tests/session_fixture.c
tests/ssh2.c
win32/libssh2_config.h

`libssh2.h` required `winsock2.h` for `_WIN32` since 81d53de4dc5ee39bd6215958c7dce3b12731195e (2011-06-04).
Apply that to the whole codebase. This makes it unnecessary to detect `HAVE_WINSOCK2_H` and allows to drop all its uses.
Completes TODO from b66d7317ca6c882afbe52fe426f68c119c40d348
TODO: Straighten out the use a mixture of `HAVE_WINDOWS_H`, `WIN32`, `_WIN32` to detect Windows.

delete redundant `HAVE_WINSOCK2_H`

---

configure.ac

No longer necessary after moving the disabling/enabling logic from build tool to `example/x11.c`.
Reverts 4774d500e724bc4e548f743a0cb644ab05599474
Follow-up to d245c66cc0029e480674394c23e8be1c9410f7ad

autotools: delete unused conditional `HAVE_SYS_UN_H`

---

.gitignore
Makefile.am
Makefile.mk

Move the GNU Make file formerly known as `win32/GNUmakefile` to the root directory from `win32`. It now supports any platform with a GCC-like toolchain, while also keeping support for win32.
For non-Windows platforms it's necessary to provide a hand-crafted `libssh2_config.h` header for now.
Usage: `make -f Makefile.mk`

Makefile.mk: move portable GNU Make file to the root

---

docs/libssh2_session_get_read_timeout.3
docs/libssh2_session_set_read_timeout.3
include/libssh2.h
src/libssh2_priv.h
src/packet.c
src/session.c
src/sftp.c

This set of changes provides a mechanism to runtime-configure the previously `#define`'d timeout for reading packets from a session.  The intention here is to also extend `libcurl` to be able to use this interface so that when fetching from sftp servers which are very slow to return directory listings, connections do not time-out so much.
The curl patches are staged here: https://github.com/danielsilverstone-ct/curl/tree/configurable-sftp-timeout but I need to adjust them for a prediction of the libssh2 version which might contain this change if accepted.

Configurable session read timeout

---

example/x11.c

If you do not add one byte for the terminating zero, then you allow the possibility of information disclosure through changing the value of the port.

example/x11: Add null-termination

---

docs/Makefile.am
docs/libssh2_channel_direct_streamlocal_ex.3
include/libssh2.h
src/channel.c

This patch allow to use direct-streamlocal service from OpenSSH 6.7, that allows UNIX socket connections.
Patch-by: @gjalves Gustavo Junior Alves
Closes #216
Closes #632
Closes #945

Support for direct-streamlocal@openssh.com UNIX socket connection

---

include/libssh2.h
src/libssh2_priv.h
src/scp.c
src/session.c

A new flag named `LIBSSH2_FLAG_QUOTE_PATHS` has been added, to make libssh2 not quote file paths sent to the remote's scp sub system. Some custom ssh daemons cannot handle quoted paths, and this makes this flag useful.

Option to not quote scp paths

---

src/libssh2_priv.h
src/mac.c
src/mac.h
src/transport.c
tests/CMakeLists.txt
tests/Makefile.am
tests/test_auth_keyboard_info_request.c

Support for calculating MAC (message authentication code) on encrypted
data instead of plain text data.
This adds support for the following MACs:
- `hmac-sha1-etm@openssh.com`
- `hmac-sha2-256-etm@openssh.com`
- `hmac-sha2-512-etm@openssh.com`
Integration-patches-by: Viktor Szakats
* rebase on master
* fix checksec warnings
* fix compiler warning
* fix indent/whitespace/eol
* rebase/manual merge onto AES-GCM patch #797
* more manual merge of `libssh2_transport_send()` based
on dfandrich/shellfish
Fixes #582
Closes #655
Closes #987
---
After rebasing to AES-GCM, the whitespace-free diff is recommended for a clearer view:
https://github.com/libssh2/libssh2/pull/987/files?w=1

support encrypt-then-mac (etm) MACs

---

src/channel.c
src/openssl.h
src/packet.c

The first merely makes sure that we include the proper header file, otherwise this fails to compile with recent versions of Xcode.
The second patch fixes an issue that would corrupt the data stream when attempting to initialize the agent in non-blocking mode, as it is necessary to propagate the EAGAIN signal upstream when the transport returns EAGAIN.

Couple of small fixes

---

src/sftp.c
src/sftp.h

Hi,
currently libssh2 cannot read huge directory listings when the package size of LIBSSH2_SFTP_PACKET_MAXLEN (256KB) is hit.
For example AWS always sends a single package with all files of a directory, no matter how big it is:
https://freefilesync.org/forum/viewtopic.php?t=10020
Package size is probably around 7 MB in this case!
LIBSSH2_SFTP_PACKET_MAXLEN is a good idea in general, but there doesn't seem to be a one size fits all.
While almost all(?) SFTP responses come in very small packages, I believe the SSH_FXP_READDIR request should be exempted.
The proposed patch, enhances the package size reading to include parsing the full SFTP packet header. And in case a package is of type SSH_FXP_NAME and matches an expected readdir_request_id, it does not fail if LIBSSH2_SFTP_PACKET_MAXLEN is …

sftp: remove packet limit for directory reading

---

src/sftp.c

This change prevents directory listing errors when attribute extensions are present by advancing stream parsing past extensions.

sftp: parse attribute extensions, if present, to avoid stream parsing errors

---

tests/test_sshd.test

The compiled in default to sshd can be a non-writable location since it
expects to be run as root.

test_sshd.test: set a safe PID directory

---

src/transport.c

The debug message for encrypting data is incorrect if the data is not a multiple of the blocksize. For example, when the blocksize is 16 and the data to be encrypted is 36 bytes long, the following debug messages are produced:
> [libssh2] 0.438857 Socket: crypting bytes 0-15
> [libssh2] 0.438857 Socket: crypting bytes 16-31
> [libssh2] 0.438857 Socket: crypting bytes 32-47
The final iteration of the encryption loop would only be encrypting bytes 33 through 36, (offsets 32-35), so the correct message would be:
> [libssh2] 2.801589 Socket: crypting bytes 32-35
This pull request updates the log message to use the computed length of the data chunk being encrypted, rather than the fixed block size.

Transport: Fix incorrect byte offset in debug message

---

src/misc.c

Before assigning a value to the outlen, we need to check whether it is NULL.
Fixes https://github.com/libssh2/libssh2/issues/1108

Add NULL pointer check for outlen before use

---

src/userauth.c

We should check whether *key_method is a NULL pointer instead of key_method

Fix a NULL pointer reference, when LIBSSH2_ALLOC() failed.

---

libssh2.pc.in

Not an autotools expert, but `LIBS` contains `libssh2`'s own dependencies, so when doing shared linking, it makes no sense to put them under `Libs: ...` in the pkg-config file. `Libs.private` is what you want to use for that, since during static linking you do have to provide transitive deps.
What's not fixed in this PR: adding the `-L` search dirs when doing static linking. Apparently when openssl has its libraries in `<prefix>/lib64`, no `-L<prefix>/lib64` is added. But when it's in `<prefix>/lib`, it is? I guess this is a matter of custom logic in libssh2's autotools stuff, where `LIBS = -L... -lssl` is used for the `lib` check (custom?), while `LDFLAGS = -L...` and `LIBS = -lssl` is used for the `lib64` check (autotools internals?)

Don't put `@LIBS@` in pc file

---

src/CMakeLists.txt
tests/CMakeLists.txt

Fixes compiling as dependency with FetchContent

cmake: CMAKE_SOURCE_DIR -> PROJECT_SOURCE_DIR

---

src/pem.c

libssh2 1.11.0 fails to decrypt private keys encrypted with aes128-gcm@openssh.com and aes256-gcm@openssh.com ciphers.
To reproduce the issue, you can create a test key with a command like the following:
```bash
ssh-keygen -Z aes256-gcm@openssh.com -f id_aes256-gcm
```
If you attempt to use this key for authentication, libssh2 will return the not-so-helpful error message "Wrong passphrase or invalid/unrecognized private key file format".
The problem is that OpenSSH encrypts keys differently than packets. It does not include the length as AAD, and the 16 byte authentication tag is appended after the encrypted key. The length of the authentication tag is not included in the encrypted key length.
I have not found any documentation for this behaviour -- I discovered it by looking at the …

Fix private keys encrypted with aes-gcm methods

---

src/userauth.c

We use different APIs  when we read one private key from memory, so it is improper to store the private key information in the structure that stores the private key file information.
Fixes https://github.com/libssh2/libssh2/issues/773
Reported-by: mike-jumper

Add a new structure to  separate memory read and file read.

---

src/libssh2_priv.h
src/packet.c

An automated fuzzer found an out of bounds read in packet_authagent_open().
And as a bonus commit, use strlen() for strings in packet.c instead of sizeof().

Properly bounds check packet_authagent_open

---

src/openssl.c
src/openssl.h

Use non-deprecated OpenSSL APIs when linking against OpenSSL 3

---

.github/workflows/ci.yml
CMakeLists.txt
configure.ac
include/libssh2.h
src/channel.c
src/libssh2_priv.h
src/scp.c
src/session.c

The following APIs have been deprecated for over 10 years and
use LIBSSH2_NO_DEPRECATED to mark them as deprecated:
libssh2_session_startup()
libssh2_banner_set()
libssh2_channel_receive_window_adjust()
libssh2_channel_handle_extended_data()
libssh2_scp_recv()
Add these options to disable them:
- autotools: `--disable-deprecated`
- cmake: `-DLIBSSH2_NO_DEPRECATED=ON`
- `CPPFLAGS`: `-DLIBSSH2_NO_DEPRECATED`
Fixes #1259
Replaces #1260
Closes #1267

build: add `LIBSSH2_NO_DEPRECATED` option

---

src/openssl.c

Toying with cppcheck and it found 4 cases of a null pointer being dereferenced in the code. There were 2 functions that called the respective sections of code that set NULL for method_len and pubkeydata_len causing the dereference when they get assigned a value without being checked.
---
https://github.com/libssh2/libssh2/pull/1304/files?w=1

openssl: fix cppcheck found NULL dereferences

---

os400/README400
os400/ccsid.c
os400/config400.default
os400/initscript.sh
os400/libssh2rpg/libssh2.rpgle.in
os400/libssh2rpg/libssh2_sftp.rpgle
os400/macros.h
os400/make.sh
os400/rpg-examples/SFTPXMPLE
src/os400qc3.c
src/os400qc3.h

- Handle MD5 conditionals in os400qc3.
- Check for errors in os400qc3 pbkdf1.
- Implement an optional build options override file.
- Sync ILE/RPG copy files with current C header files.
- Allow a null session within a string conversion cache.
- Add an ILE/RPG example.
- Adjust outdated copyrights in changed files.

os400: maintain up to date

---

src/openssl.c

I've begun the process of merging the current master branch into our repo. Previouslly, we were cherry-picking commits or manually applying them to our repo, due to changes we had made which were wholly incompatible with the AES-GCM changes made last year. My goal is to get things in a place where we can upstream the remaining changes from our repo, including `chacha20-poly1305@openssh.com` support, and then get in the habit of upstreaming our improvements more quickly so that we're not maintaining radically different versions of the code.
When running the current master branch through our internal test suite however, I noticed crashes and assert failures that must not be getting executed by the project's test suite. (However, I have never been able to get libssh2's test suite to run on …

gen_publickey_from_dsa: Initialize BIGNUMs to NULL for OpenSSL 3

---

src/mac.c

mac_method_hmac_aesgcm currently sets its hash functions to NULL. This is typically fine, when both the local and remote session are using mac_method_hmac_aesgcm. But it's possible to set just one of the sessions to use e.g. aes128-ctr, and if you do that, the hash functions will get called without first checking if they're NULL or not.
This may be a misconfiguration which will prevent a proper connection, but it's better that libssh2 not defererence NULL in this circunstance.

Supply empty hash functions for mac_method_hmac_aesgcm to avoid a crash when e.g. setting LIBSSH2_METHOD_CRYPT_CS

---

docs/INSTALL_AUTOTOOLS

corrected --with-libmbedtls-prefix to current option --with-libmbedcrypto-prefix
Edit:
Updated to latest version at time of writing (1.11.0) and scripting up build process for libssh2 which will use mbedTLS as crypto backend, installed in a non-standard location. 
Docs mentioned `--with-libmbedtls-prefix` which resulted in:
```
configure: WARNING: unrecognized options: --with-libmbedtls-prefix
configure: error: Required dependencies are missing!
```
However, using `--with-libmbedcrypto-prefix` seems to work OK.

docs: update INSTALL_AUTOTOOLS

---

src/kex.c

KEX pseudo-methods "ext-info-c" and "kex-strict-c-v00@openssh.com" must be kept in list in libssh2_session_method_pref() to properly announce available extensions.
Fixes #1326

kex: always add extension indicators to kex_algorithms

---

src/transport.c

We should check if encrypt-then-MAC feature is enabled in remote end's configuration.
Closes #1331

transport: check ETM on remote end when receiving

---

tests/openssh_server/Dockerfile

The unexplained CI fallouts are gone with the latest debian:testing (20240330).
Ref #1328 #1329 #1338.
Closes #1346

ci: revert to debian:testing-slim after xz backdoor removal

---

src/kex.c
src/openssl.c
src/openssl.h
src/os400qc3.c
src/os400qc3.h
src/wincng.c
src/wincng.h

Found by oss-fuzz. In `diffie_hellman_sha_algo()`, we were calling
`_libssh2_bn_from_bin()` with data recieved by the server without
checking whether that data was zero-length or ridiculously long.
In the OpenSSL backend, this would cause `_libssh2_bn_from_bin()`
to fail an allocation, which would eventually lead to a NULL
dereference when the bignum was used.
Add the same check for `_libssh2_bn_set_word()` and
`_libssh2_bn_to_bin()`.

src: check the return value from `_libssh2_bn_*()` functions

---

.github/workflows/ci.yml

GHA macOS runners became ARM64 machines. Make the Homebrew prefix
dynamic to adapt to these installations.
Closes #1373

ci/GHA: fixup Homebrew location (for ARM runners)

---

.github/workflows/ci.yml

Also enable verbose for macOS `make` step.

ci/GHA: fix verbose option for autotools jobs

---

.github/workflows/ci.yml

mbedtls configure fails to detect anything due to this:
```
configure:23101: gcc -o conftest -g -O2 -I/opt/homebrew/include  conftest.c  -lmbedcrypto -lz >&5
ld: library 'mbedcrypto' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

ci/GHA: fix gcrypt with autotools/macOS/Homebrew/ARM64

---

src/openssl.c

Caught this while merging into Panic's libssh2 repo, but I probably missed it in code review earlier. My goal is to upstream all the changes from our repo, so more pull requests coming soon.

OpenSSL 3: Fix calculating DSA public key

---

src/sftp.h

Finally back to submitting patches upstream. This one's real small. I'll have another small one soon, and then a couple large ones.
According to the spec SFTP_HANDLE_MAXLEN should be 256. However, we had a customer contact us to explain that they weren't able to download or upload files with long paths in our products, but were able to do so in OpenSSH.
As it turns out, OpenSSH enforces a much larger maximum handle length than 256. So this change updates to match.

Increase SFTP_HANDLE_MAXLEN back to 4092

---

src/kex.c

Another small change. A while back, we submitted a change to check the return value of `_libssh2_bn_set_word` in the hope that it would fix a report from an open-source fuzzer. It did not. Our current theory is that the fuzzer is running out of memory, but we won't know for sure until this gets merged.

Always check for null pointers before calling _libssh2_bn_set_word

---

src/mbedtls.c

In the failure case, mbedtls_pk_context could be free'd without first being initialized.

Always init mbedtls_pk_context

---

src/transport.c

This is the patch described in #1397 
I've tested this branch and I cannot reproduce the bug in #1431 anymore with it.
I've provided a description of the bug in the commit message.

Fix unstable connections over nonblocking sockets

---

cmake/CopyRuntimeDependencies.cmake

```
CMake Warning (dev) at cmake/CopyRuntimeDependencies.cmake:59 (add_custom_command):
The following keywords are not supported when using
add_custom_command(TARGET): DEPENDS.
Policy CMP0175 is not set: add_custom_command() rejects invalid arguments.
Run "cmake --help-policy CMP0175" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
Call Stack (most recent call first):
example/CMakeLists.txt:58 (add_target_to_copy_dependencies)
```
```
CMake Warning (dev) at cmake/CopyRuntimeDependencies.cmake:59 (add_custom_command):
Exactly one of PRE_BUILD, PRE_LINK, or POST_BUILD must be given.  Assuming
POST_BUILD to preserve backward compatibility.
Policy CMP0175 is not set: add_custom_command() rejects invalid arguments.
Run "cmake --help-policy …
```

cmake: fix cmake warnings

---

appveyor.yml

in WinCNG builds, e.g. VS2015, WinCNG, x86, Server 2016:
```
Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At line:10 char:16
+   if(Test-Path $env:OPENSSL_ROOT_DIR) {
+                ~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCommand
```
https://ci.appveyor.com/project/libssh2org/libssh2/builds/51280178/job/9ddtkb91w54si3da#L85

ci/appveyor: fix PowerShell warning

---

src/sftp.c
src/userauth.c

Notes:
Fix possible memory leaks if `userauth_list()` is called more than once, e.g. an auth error case. 
Author:
Will Cosgrove
Credit:
pyscripter

userauth.c: fix possible memory leaks #1504

---

src/CMakeLists.txt

Co-authored-by: Kai Pastor
Ref: https://github.com/curl/curl/commit/f72b84809216657e4ad3c1a0184775c911080d63
Ref: https://github.com/curl/curl/pull/16233

cmake: exclude `CMAKE_C_IMPLICIT_LINK_DIRECTORIES` from `libssh2.pc`

---

src/misc.c

Make sure to allocate enough space for malformed base64 encoded data.  Changed signed size values to unsigned to match input so we can't possibly truncate input.
Credit:
Stanislav Osipov

_libssh2_base64_decode() handle malformed data

---

src/kex.c

Fixes #1553. Restores error case if user passes in invalid KEX method value to `libssh2_session_method_pref`.
Credit:
Amy Lin

Return error if user KEX methods are invalid #1553

---

src/session.c
src/session.h

Session null checks to quiet fuzzer errors if you try and start a connection with a null session.

Session null checks to quiet fuzzer

---

src/transport.c

This is a fix for my bug report here:
https://github.com/libssh2/libssh2/issues/1580
Connection fails when using one encryption method with integrated MAC and one without

fix for issue 1580

---

docs/libssh2_scp_recv.3
docs/libssh2_scp_recv2.3
docs/libssh2_scp_send64.3
src/scp.c

As described in #1624 there is a crash when the path argument is set
to NULL. In addition to the send function I also found that receive
function to have the same issue and applied the fix to both functions.
Reported-by: Liu Xing Yu
Fixes #1624

scp: fix NULL dereference in path arg of send/recv

---

src/sftp.c

Add bounds checking to public SFTP API input to avoid possible heap corruption when passing in invalid values.
Credit:
[Oblivionsage](https://github.com/Oblivionsage)

Add input bounds checking to SFTP API

---

src/sftp.c

Downcast size_t values to uint32_t before comparing so the addition isn't upcast to size_t. 
Credit: 
Joshua Rogers

Downcast packet length checks #1707
